---
all:
  children:
    managed_hosts:
      children:
        gcp:
          hosts:
            retn0-srv-gcp-01:
              ansible_host: 100.80.30.12
        oci:
          hosts:
            retn0-srv-oci-01:
              ansible_host: 100.80.30.10
            retn0-srv-oci-02:
              ansible_host: 100.80.30.11
