name: beszel-hub

services:
  beszel-hub:
    image: henrygd/beszel:0.21.0
    container_name: beszel-hub
    init: true
    restart: unless-stopped
    environment:
      APP_URL: ${BESZEL_APP_URL:?}
      CHECK_UPDATES: "true"
    networks:
      - caddy-network
    volumes:
      - beszel-data:/beszel_data
    healthcheck:
      test: ["CMD", "/beszel", "health", "--url", "http://localhost:8090"]
      interval: 120s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  caddy-network:
    name: caddy-network
    external: true

volumes:
  beszel-data:
